version: 2
build:
  os: ubuntu-22.04
  tools:
    python: "3"
python:
  install:
    {%- if not cookiecutter.prefix %}
    - requirements: modules/{{ cookiecutter.module_name }}/doc/requirements-doc.txt
    {%- else %}
    - requirements: doc/requirements-doc.txt
    {%- endif %}
sphinx:
  {%- if not cookiecutter.prefix %}
  configuration: modules/{{ cookiecutter.module_name }}/doc/conf.py
  {%- else %}
  configuration: doc/conf.py
  {%- endif %}
